import { addRandomTile, canMove, emptyGrid, moveGridWithMotion } from "./engine.js";import{loadScores,recordScore,saveScores}from"./records.js";
const board=document.querySelector("#board"),tiles=document.querySelector("#tiles"),scoreEl=document.querySelector("#score"),bestEl=document.querySelector("#best"),undoButton=document.querySelector("#undo"),message=document.querySelector("#message");
let grid,score=0,history=[],gesture=null,best=Number(localStorage.getItem("tzt-2048-best")||0),animating=false,queuedDirection=null,records=loadScores(),runId="";const scoreRecords=document.querySelector("#scoreRecords");
bestEl.textContent=best;
if(best>0&&!records.length)records=saveScores(recordScore(records,{id:"legacy-best",score:best,maxTile:2,achievedAt:""}));
function renderRecords(){scoreRecords.innerHTML=records.length?records.map((item,index)=>`<li><i>${index+1}</i><div><strong>${item.score.toLocaleString()}</strong><small>最高方块 ${item.maxTile}</small></div><b>${index===0?"BEST":"#"+(index+1)}</b></li>`).join(""):'<li class="empty">完成合并后，这里会保存你的最高分</li>'}
function tileElement(value,row,col,className=""){const element=document.createElement("div");element.className=`tile ${className}`;element.dataset.v=value;element.style.setProperty("--r",row);element.style.setProperty("--c",col);element.textContent=value;return element;}
function render({newTile=null,merges=[]}={}){const mergeSet=new Set(merges.map(([r,c])=>`${r}-${c}`));tiles.replaceChildren();grid.forEach((row,r)=>row.forEach((value,c)=>{if(!value)return;const key=`${r}-${c}`;tiles.append(tileElement(value,r,c,key===newTile?"tile-new":mergeSet.has(key)?"tile-merged":""));}));scoreEl.textContent=score;best=Math.max(best,score);bestEl.textContent=best;localStorage.setItem("tzt-2048-best",best);undoButton.disabled=!history.length||animating;}
function animateMotion(motions){const layer=document.createElement("div");layer.className="motion-layer";tiles.classList.add("tiles-hidden");board.append(layer);const animations=motions.map(motion=>{const ghost=tileElement(motion.value,motion.from[0],motion.from[1],`tile-ghost${motion.merge?" merging":""}`);layer.append(ghost);const dr=motion.to[0]-motion.from[0],dc=motion.to[1]-motion.from[1];return ghost.animate([{transform:"translate3d(0,0,0) scale(1)"},{transform:`translate3d(calc(${dc} * (100% + var(--gap))),calc(${dr} * (100% + var(--gap))),0) scale(${motion.merge?.96:1})`}],{duration:220,easing:"cubic-bezier(.22,.76,.24,1)",fill:"forwards"}).finished;});return Promise.allSettled(animations).then(()=>{layer.remove();tiles.classList.remove("tiles-hidden")});}
function start(){grid=addRandomTile(addRandomTile(emptyGrid()));score=0;history=[];animating=false;queuedDirection=null;runId=`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;message.textContent="滑动数字，相同方块会合并";render();renderRecords();[...tiles.children].forEach(tile=>tile.classList.add("tile-new"));}
async function move(direction){if(animating){queuedDirection=direction;return;}const result=moveGridWithMotion(grid,direction);if(!result.moved)return;animating=true;history.push({grid:grid.map(r=>[...r]),score});undoButton.disabled=true;const settled=result.grid;grid=addRandomTile(settled);score+=result.gained;let newTile=null;grid.forEach((row,r)=>row.forEach((value,c)=>{if(value&&!settled[r][c])newTile=`${r}-${c}`}));render({newTile,merges:result.merges});await animateMotion(result.motions);render({newTile,merges:result.merges});if(result.gained){records=saveScores(recordScore(records,{id:runId,score,maxTile:Math.max(...grid.flat()),achievedAt:new Date().toISOString()}));renderRecords();scoreEl.animate([{transform:"scale(1)",color:"#164c5b"},{transform:"scale(1.22)",color:"#ff765f"},{transform:"scale(1)",color:"#164c5b"}],{duration:330,easing:"ease-out"})}animating=false;undoButton.disabled=!history.length;if(grid.some(row=>row.includes(2048)))message.textContent="你合成了 2048！还可以继续挑战";else if(!canMove(grid))message.textContent="没有可移动的位置了，悔棋或开始新游戏";if(queuedDirection){const next=queuedDirection;queuedDirection=null;move(next);}}
function endGesture(event){if(!gesture)return;const dx=event.clientX-gesture.x,dy=event.clientY-gesture.y;gesture=null;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"down":"up"));}
board.addEventListener("pointerdown",e=>{if(e.button!==undefined&&e.button!==0)return;gesture={x:e.clientX,y:e.clientY};board.setPointerCapture?.(e.pointerId)});board.addEventListener("pointerup",endGesture);board.addEventListener("pointercancel",()=>gesture=null);board.addEventListener("pointermove",e=>{if(gesture)e.preventDefault()});
addEventListener("keydown",e=>{const direction={ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right",ArrowUp:"up",w:"up",W:"up",ArrowDown:"down",s:"down",S:"down"}[e.key];if(direction){e.preventDefault();move(direction)}});document.querySelectorAll("[data-direction]").forEach(b=>b.addEventListener("click",()=>move(b.dataset.direction)));document.querySelector("#newGame").addEventListener("click",start);undoButton.addEventListener("click",()=>{if(animating)return;const previous=history.pop();if(!previous)return;grid=previous.grid;score=previous.score;message.textContent="已撤销上一步";render();[...tiles.children].forEach(tile=>tile.classList.add("tile-restored"))});start();
