import { addRandomTile, canMove, emptyGrid, moveGridWithMotion } from "./engine.js";import{loadScores,recordScore,saveScores}from"./records.js";
import { hasGlobalPlayer, initGlobalLeaderboard } from "../shared/leaderboard.js";
const board=document.querySelector("#board"),tiles=document.querySelector("#tiles"),scoreEl=document.querySelector("#score"),bestEl=document.querySelector("#best"),undoButton=document.querySelector("#undo"),message=document.querySelector("#message");
let grid,score=0,history=[],gesture=null,best=Number(localStorage.getItem("tzt-2048-best")||0),animating=false,queuedDirection=null,records=loadScores(),runId="",tileSequence=0;const scoreRecords=document.querySelector("#scoreRecords");
const worldBoard=initGlobalLeaderboard({gameId:"2048",mode:"classic",title:"2048 全球最高分榜",formatValue:value=>Number(value).toLocaleString()});
let worldSubmitTimer=null;
function submitWorldScore(immediate=false){if(!hasGlobalPlayer()||score<2)return;clearTimeout(worldSubmitTimer);const send=()=>worldBoard.submit({score,runId,metadata:{max_tile:Math.max(...grid.flat()),moves:history.length}});if(immediate)send();else worldSubmitTimer=setTimeout(send,1800)}
bestEl.textContent=best;
if(best>0&&!records.length)records=saveScores(recordScore(records,{id:"legacy-best",score:best,maxTile:2,achievedAt:""}));
function renderRecords(){scoreRecords.innerHTML=records.length?records.map((item,index)=>`<li><i>${index+1}</i><div><strong>${item.score.toLocaleString()}</strong><small>最高方块 ${item.maxTile}</small></div><b>${index===0?"BEST":"#"+(index+1)}</b></li>`).join(""):'<li class="empty">完成合并后，这里会保存你的最高分</li>'}
function tileElement(value,row,col,className=""){const element=document.createElement("div");element.className=`tile ${className}`;element.dataset.tileId=String(++tileSequence);placeTile(element,value,row,col);return element;}
function placeTile(element,value,row,col){element.dataset.v=value;element.dataset.row=row;element.dataset.col=col;element.style.setProperty("--r",row);element.style.setProperty("--c",col);if(element.textContent!==String(value))element.textContent=value;}
function updateStats(){if(scoreEl.textContent!==String(score))scoreEl.textContent=score;best=Math.max(best,score);if(bestEl.textContent!==String(best))bestEl.textContent=best;localStorage.setItem("tzt-2048-best",best);undoButton.disabled=!history.length||animating;}
function render({newTile=null,merges=[]}={}){const mergeSet=new Set(merges.map(([r,c])=>`${r}-${c}`));tiles.replaceChildren();grid.forEach((row,r)=>row.forEach((value,c)=>{if(!value)return;const key=`${r}-${c}`;tiles.append(tileElement(value,r,c,key===newTile?"tile-new":mergeSet.has(key)?"tile-merged":""));}));updateStats();}
async function animateMotion(motions){const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;tiles.querySelectorAll(".tile-new,.tile-merged,.tile-restored").forEach(tile=>tile.classList.remove("tile-new","tile-merged","tile-restored"));board.classList.add("board-moving");const records=motions.map(motion=>{const element=tiles.querySelector(`[data-row="${motion.from[0]}"][data-col="${motion.from[1]}"]`);if(!element)return{motion,element:null,animation:null};const dr=motion.to[0]-motion.from[0],dc=motion.to[1]-motion.from[1],moves=dr!==0||dc!==0;element.classList.add("tile-moving");const animation=moves?element.animate([{transform:"translate3d(0,0,0) scale(1)"},{transform:`translate3d(calc(${dc} * (100% + var(--gap))),calc(${dr} * (100% + var(--gap))),0) scale(${motion.merge?.96:1})`}],{duration:reduced?1:210,easing:"cubic-bezier(.22,.76,.24,1)",fill:"forwards"}):null;return{motion,element,animation};});await Promise.allSettled(records.filter(item=>item.animation).map(item=>item.animation.finished));return records;}
function settleMotion(records,settled,newTile,merges){const destinations=new Map();records.forEach(record=>{if(!record.element)return;const key=record.motion.to.join("-");if(!destinations.has(key))destinations.set(key,[]);destinations.get(key).push(record);});const mergeSet=new Set(merges.map(([r,c])=>`${r}-${c}`));destinations.forEach((group,key)=>{const [row,col]=group[0].motion.to,keeper=group[0].element;placeTile(keeper,settled[row][col],row,col);group.forEach(({element,animation},index)=>{animation?.cancel();element.classList.remove("tile-moving");if(index)element.remove();});if(mergeSet.has(key))keeper.classList.add("tile-merged");});board.classList.remove("board-moving");if(newTile){const[row,col]=newTile.split("-").map(Number);tiles.append(tileElement(grid[row][col],row,col,"tile-new"));}updateStats();}
function start(){grid=addRandomTile(addRandomTile(emptyGrid()));score=0;history=[];animating=false;queuedDirection=null;runId=`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;message.textContent="滑动数字，相同方块会合并";render();renderRecords();[...tiles.children].forEach(tile=>tile.classList.add("tile-new"));}
async function move(direction){if(animating){queuedDirection=direction;return;}const result=moveGridWithMotion(grid,direction);if(!result.moved)return;animating=true;history.push({grid:grid.map(r=>[...r]),score});undoButton.disabled=true;const settled=result.grid,nextGrid=addRandomTile(settled),nextScore=score+result.gained;let newTile=null;nextGrid.forEach((row,r)=>row.forEach((value,c)=>{if(value&&!settled[r][c])newTile=`${r}-${c}`}));const motionRecords=await animateMotion(result.motions);grid=nextGrid;score=nextScore;settleMotion(motionRecords,settled,newTile,result.merges);if(result.gained){records=saveScores(recordScore(records,{id:runId,score,maxTile:Math.max(...grid.flat()),achievedAt:new Date().toISOString()}));renderRecords();submitWorldScore();scoreEl.animate([{transform:"scale(1)"},{transform:"scale(1.16)"},{transform:"scale(1)"}],{duration:260,easing:"ease-out"})}animating=false;undoButton.disabled=!history.length;if(grid.some(row=>row.includes(2048)))message.textContent="你合成了 2048！还可以继续挑战";else if(!canMove(grid)){message.textContent="没有可移动的位置了，悔棋或开始新游戏";submitWorldScore(true)}if(queuedDirection){const next=queuedDirection;queuedDirection=null;move(next);}}
function endGesture(event){if(!gesture)return;const dx=event.clientX-gesture.x,dy=event.clientY-gesture.y;gesture=null;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"down":"up"));}
board.addEventListener("pointerdown",e=>{if(e.button!==undefined&&e.button!==0)return;gesture={x:e.clientX,y:e.clientY};board.setPointerCapture?.(e.pointerId)});board.addEventListener("pointerup",endGesture);board.addEventListener("pointercancel",()=>gesture=null);board.addEventListener("pointermove",e=>{if(gesture)e.preventDefault()});
addEventListener("keydown",e=>{const direction={ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right",ArrowUp:"up",w:"up",W:"up",ArrowDown:"down",s:"down",S:"down"}[e.key];if(direction){e.preventDefault();move(direction)}});document.querySelectorAll("[data-direction]").forEach(b=>b.addEventListener("click",()=>move(b.dataset.direction)));document.querySelector("#newGame").addEventListener("click",start);undoButton.addEventListener("click",()=>{if(animating)return;const previous=history.pop();if(!previous)return;grid=previous.grid;score=previous.score;message.textContent="已撤销上一步";render();[...tiles.children].forEach(tile=>tile.classList.add("tile-restored"))});start();
