import { addRandomTile, canMove, emptyGrid, moveGrid } from "./engine.js";
const board=document.querySelector("#board"),tiles=document.querySelector("#tiles"),scoreEl=document.querySelector("#score"),bestEl=document.querySelector("#best"),undoButton=document.querySelector("#undo"),message=document.querySelector("#message");
let grid,score=0,history=[],gesture=null,best=Number(localStorage.getItem("tzt-2048-best")||0);
bestEl.textContent=best;
function positions(){return new Map([...tiles.children].map(el=>[el.dataset.key,el.getBoundingClientRect()]));}
function render(before=new Map(),isNew=false){tiles.replaceChildren();const seen={};grid.forEach((row,r)=>row.forEach((value,c)=>{if(!value)return;seen[value]=(seen[value]||0)+1;const el=document.createElement("div");el.className="tile";el.dataset.v=value;el.dataset.key=`${value}-${seen[value]}`;el.style.setProperty("--r",r);el.style.setProperty("--c",c);el.textContent=value;tiles.append(el);}));requestAnimationFrame(()=>[...tiles.children].forEach(el=>{const old=before.get(el.dataset.key),now=el.getBoundingClientRect();if(old)el.animate([{transform:`translate(${old.left-now.left}px,${old.top-now.top}px)`},{transform:"translate(0,0)"}],{duration:155,easing:"cubic-bezier(.2,.85,.25,1)"});else if(isNew)el.animate([{transform:"scale(.55)",opacity:.35},{transform:"scale(1)",opacity:1}],{duration:150,easing:"cubic-bezier(.2,.9,.3,1.25)"});}));scoreEl.textContent=score;best=Math.max(best,score);bestEl.textContent=best;localStorage.setItem("tzt-2048-best",best);undoButton.disabled=!history.length;}
function start(){grid=addRandomTile(addRandomTile(emptyGrid()));score=0;history=[];message.textContent="滑动数字，相同方块会合并";render(new Map(),true)}
function move(direction){const result=moveGrid(grid,direction);if(!result.moved)return;const before=positions();history.push({grid:grid.map(r=>[...r]),score});grid=addRandomTile(result.grid);score+=result.gained;render(before,true);if(grid.some(row=>row.includes(2048)))message.textContent="你合成了 2048！还可以继续挑战";else if(!canMove(grid))message.textContent="没有可移动的位置了，悔棋或开始新游戏";}
function endGesture(event){if(!gesture)return;const dx=event.clientX-gesture.x,dy=event.clientY-gesture.y;gesture=null;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"down":"up"));}
board.addEventListener("pointerdown",e=>{if(e.button!==undefined&&e.button!==0)return;gesture={x:e.clientX,y:e.clientY};board.setPointerCapture?.(e.pointerId)});board.addEventListener("pointerup",endGesture);board.addEventListener("pointercancel",()=>gesture=null);board.addEventListener("pointermove",e=>{if(gesture)e.preventDefault()});
addEventListener("keydown",e=>{const direction={ArrowLeft:"left",a:"left",A:"left",ArrowRight:"right",d:"right",D:"right",ArrowUp:"up",w:"up",W:"up",ArrowDown:"down",s:"down",S:"down"}[e.key];if(direction){e.preventDefault();move(direction)}});document.querySelectorAll("[data-direction]").forEach(b=>b.addEventListener("click",()=>move(b.dataset.direction)));document.querySelector("#newGame").addEventListener("click",start);undoButton.addEventListener("click",()=>{const previous=history.pop();if(!previous)return;grid=previous.grid;score=previous.score;message.textContent="已撤销上一步";render()});start();
