(function () {
  'use strict';
  const supported=['en','ja','fr','es','ru','it','ar','ko','zh-CN','zh-TW','pt'];
  const labels={en:'English',ja:'日本語',fr:'Français',es:'Español',ru:'Русский',it:'Italiano',ar:'العربية',ko:'한국어','zh-CN':'简体中文','zh-TW':'繁體中文',pt:'Português'};
  const normalize=value=>{const raw=(value||'en').replace('_','-'),lower=raw.toLowerCase();if(supported.includes(raw))return raw;if(['zh-hant','zh-hk','zh-mo'].includes(lower))return'zh-TW';if(lower.startsWith('zh'))return'zh-CN';return supported.find(x=>x.toLowerCase().startsWith(lower.split('-')[0]))||'en'};
  const params=new URLSearchParams(location.search);
  const locale=normalize(params.get('lang')||localStorage.getItem('tzt-game-language')||navigator.language);
  window.__TZT_GAME_LOCALE=locale;
  try{if(window.opener?.GAME_I18N_BOOTSTRAP===locale)window.opener.GAME_I18N_BOOTSTRAP=null;else window.opener?.GAME_I18N_BOOTSTRAP&&void 0}catch{}
  localStorage.setItem('tzt-game-language',locale);document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';

  const en={
    '游戏大厅':'Game lobby','返回游戏大厅':'Return to game lobby','返回大厅':'Back to lobby','重新设置':'Reset setup','重新开始':'Restart','返回菜单':'Return to menu','继续':'Resume','声音':'Sound',
    '经典纸牌游戏':'Classic card game','蜘蛛纸牌':'Spider Solitaire','选择难度':'Choose difficulty','简单':'Easy','中等':'Medium','困难':'Hard','单花色':'One suit','双花色':'Two suits','四花色':'Four suits','每日挑战':'Daily challenge','每日固定牌局':'Daily fixed deal','新游戏':'New game','提示':'Hint','无限':'Unlimited','无限次数提示':'Unlimited hints','难度':'Difficulty','步数':'Moves','已完成':'Completed','本局用时':'Time','点击发牌':'Deal cards','玩法':'How to play','每日挑战排行榜':'Daily challenge leaderboard','今日尚未完成':'Not completed today','挑战完成':'Challenge complete','漂亮的一局！':'Great game!','再来一局':'Play again','蜘蛛纸牌牌桌':'Spider Solitaire table','已完成牌组':'Completed runs','发下一排牌':'Deal next row','背面牌':'Face-down card','今日最佳':'Today’s best','步完成':'moves',
    '牌点递减即可叠放，同花色连续牌组可以整体移动；空列可放任意牌。':'Stack in descending order. Same-suit runs move together; any card may enter an empty column.','完成每日挑战后，这里会记录你的完成速度':'Complete the daily challenge to record your time here.','把同花色的 K 到 A 连成完整序列':'Build complete same-suit runs from K to A','只有同花色、连续递减的亮牌可以整体移动':'Only descending face-up cards of the same suit move together.','已选中牌组，请点击目标列':'Run selected. Choose a destination column.','目标牌必须比移动牌大一点，空列则可以放任意牌':'Destination must be one rank higher; empty columns accept any card.','八组牌全部完成！':'All eight runs are complete!','移动成功':'Move complete','牌已经全部发完了':'All stock cards have been dealt.','补牌前，每一列都必须至少有一张牌':'Every column needs a card before dealing.','已向每列补发一张牌':'One card dealt to every column.','当前没有合适移动，试试发下一排牌':'No useful move. Try dealing the next row.','先把空列补上牌，才能继续发牌':'Fill empty columns before dealing.','暂时没有可用移动，可以重新开一局':'No moves are available. Start a new game.','今日固定牌局 · 按完成速度进入排行榜':'Today’s fixed deal · ranked by completion time','每日挑战速度排行榜':'Daily challenge speed leaderboard','，这一步能翻开暗牌':'; this reveals a face-down card','，可以接成同花序列':'; this extends a same-suit run','提示：把第':'Hint: move column ','列移到第':' to column ','第':'','列，共':' column, ','张牌':' cards',
    '麻雀':'Mahjong','东一局':'East 1','东一':'East 1','本场':'Honba','每一次出牌，':'Every discard ','都有迹可循。':'has a reason.','一款专注牌效与决策训练的单机日麻。先凭直觉落子，再听 AI 解释另一种可能。':'Single-player riichi mahjong focused on tile efficiency and decisions. Play by instinct, then compare the AI advice.','开始一局':'Start a match','人数':'Players','四人麻将':'Four-player','三人麻将':'Three-player','局数':'Match length','一局战':'Single hand','东风战':'East round','半庄战':'Hanchan','模式':'Mode','AI 教练':'AI coach','实时分析候选牌与进张':'Live discard and ukeire analysis','普通对局':'Standard game','纯净界面，独立思考':'Clean table for independent play','进入牌桌':'Enter table','吃碰杠对局 · 完整符番点数 · 役满判定':'Chi / Pon / Kan · full scoring · yakuman','四家副露':'All melds','宝牌表示':'Dora indicator','四家牌河':'All rivers','玩家':'You','北川':'Kitagawa','小林':'Kobayashi','出牌':'Discard','鸣牌':'Call','出牌建议':'Discard advice','收起':'Collapse','展开':'Expand','选择一张牌后，AI 会比较向听数与有效进张。':'Select a tile and the AI compares shanten and effective draws.','点':'points','请选择一张牌打出':'Choose a tile to discard.','你的手牌':'Your hand','可用操作':'Available actions','吃牌组合':'Chi choices','立直':'Riichi','两立直':'Double riichi','自摸':'Tsumo','荣和':'Ron','碰':'Pon','杠':'Kan','吃':'Chi','跳过':'Pass','流局':'Draw','东家':'East seat','门前清自摸和':'Menzen tsumo','和牌牌型':'Winning hand','副露牌型':'Open melds','和牌役种':'Yaku','役种明细':'Yaku details','点数移动':'Score movement','查看分数变化':'View score changes','返回设置并结束当前对局？':'End this match and return to setup?','你的回合：选择一张牌打出':'Your turn: choose a tile to discard.','对手思考中…':'Opponent is thinking…','立直中：请选择摸切牌':'Riichi: discard the drawn tile.','立直宣言后，只能打出保持听牌的牌':'After declaring riichi, discard only a tile that keeps tenpai.','立直后必须摸切刚摸到的牌':'After riichi, discard the tile just drawn.','成立：请选择一张牌打出':' called: choose a discard.','杠后补牌：请选择一张牌打出':'Kan replacement drawn: choose a discard.','荒牌流局':'Exhaustive draw','牌山已尽，本局无人和牌。':'The wall is empty. No player won.','本局无人支付点数':'No points were paid.','无人和牌 · 进入点数确认':'No winner · review scores','本局没有点数移动':'No score movement.','下一局':'Next hand','返回模式选择':'Return to mode selection','等待你的下一次摸牌…':'Waiting for your next draw…','和牌':'Winning hand','听牌':'Tenpai','向听':'shanten','推荐':'Recommended','候选':'Candidate','枚进张':'ukeire','种有效牌':'effective tiles','余':'Wall ','立直棒':'Riichi sticks','符':'Fu','番':'Han','得点':'Points','役满':'Yakuman','满贯':'Mangan','放铳支付':'Ron payment','自摸支付':'Tsumo payment','场上立直棒':'Riichi sticks','你获得':'You gain','你需要支付':'You pay','你本局没有点数变化':'Your score did not change.','断幺九':'All Simples','断幺':'All Simples','平和':'Pinfu','一杯口':'Pure Double Sequence','役牌':'Value Tiles','七对子':'Seven Pairs','对对和':'All Triplets','三暗刻':'Three Concealed Triplets','混一色':'Half Flush','清一色':'Full Flush','岭上开花':'After a Kan','海底摸月':'Last Tile Draw','河底捞鱼':'Last Tile Ron','一发':'Ippatsu',
    '赛车':'Racing','以 2.5 桌面版为基线，保留五条真实赛道、赛车线、刹车提示、计时赛与十车正赛。':'Five circuits, racing line, braking hints, time trial, and ten-car races based on the 2.5 desktop version.','斯帕-弗朗科尔尚':'Spa-Francorchamps','银石':'Silverstone','蒙扎':'Monza','摩纳哥':'Monaco','上海国际赛车场':'Shanghai International Circuit','比赛设置':'Session setup','赛道':'Track','计时赛':'Time trial','正赛 · 10 辆车':'Race · 10 cars','AI 难度':'AI difficulty','视野':'View','近':'Near','标准':'Standard','宽':'Wide','涂装':'Livery','进入赛道':'Enter track','键盘 W/S/A/D · 手柄摇杆与扳机 · R / A 复位 · P / START 暂停':'Keyboard W/S/A/D · gamepad sticks and triggers · R/A reset · P/START pause','出发前，记住四件事':'Four things before you drive','平顺输入':'Smooth inputs','高速时转向锁自动减小。先制动，再逐渐转向。':'Steering lock reduces at speed. Brake first, then turn progressively.','读取赛车线':'Read the racing line','全油门':'Full throttle','收油':'Lift','制动':'Brake','利用路肩':'Use the kerbs','红白路肩可以使用，但驶出赛道会删除圈速或累计警告。':'Use the red-white kerbs; leaving the track invalidates laps or adds warnings.','建立 Delta':'Build a delta','完成一个有效圈后，实时比较自己的个人最快圈。':'After a valid lap, compare live with your personal best.','开始驾驶':'Start driving','切换赛车线':'Toggle racing line','比赛暂停':'Session paused','回到 3 秒前':'Return to 3 seconds ago','车辆复位中':'Resetting car','触屏控制':'Touch controls','车辆已重置':'Car reset','已回到 3 秒前 · 本圈无效':'Returned 3 seconds · lap invalid','禁止逆向行驶':'Wrong way is not allowed','逆向行驶 · 已重置':'Wrong way · car reset','圈速已删除 · 赛道限制':'Lap deleted · track limits','罚时 5 秒 · 赛道限制':'5-second penalty · track limits','赛道限制警告':'Track-limit warning','个人最快圈':'Personal best','无效圈 · 成绩未记录':'Invalid lap · time not recorded','比赛完成 · 最快圈':'Race complete · fastest lap','比赛完成':'Race complete','正在准备玩具赛道…':'Preparing the toy circuit…','赛道加载失败':'Track failed to load','请通过网站服务器打开本页面，而不是直接双击 HTML 文件。':'Open this page through a web server instead of double-clicking the HTML file.',
    '德州扑克':'Texas Hold’em','沈砚':'Shen Yan','阿岚':'Alan','老周':'Zhou','白露':'Bailu','局':'','盲注':'Blinds','随机牌组':'Shuffled deck','每日签到':'Daily bonus','今日已签':'Claimed today','美东 00:00 刷新':'Resets 00:00 ET','底池':'Pot','本局结算':'Hand result','翻牌前':'Pre-flop','翻牌':'Flop','转牌':'Turn','河牌':'River','本局胜者':'Winner','赢得':'wins','筹码':'chips','思考中':'Thinking','对局信息':'Table info','牌局信息':'Table info','关闭牌局信息':'Close table info','对手行动与当前局势':'Opponent actions and situation','当前牌力参考':'Estimated hand strength','根据已知牌面估算，仅供牌桌决策参考':'Estimated from visible cards; use as a guide only.','本局已弃牌':'Folded this hand','开牌结果':'Showdown','下注历史':'Bet history','最新在上':'Newest first','阶段':'Street','动作':'Action','筹码已经输光':'You are out of chips','领取今日签到即可继续':'Claim today’s bonus to continue.','请在美东时间 00:00 后回来签到':'Return after 00:00 ET for the next bonus.','签到领取 1,000':'Claim 1,000','开始新一局':'Start next hand','当前筹码':'Current chips','自动保存':'auto-saved','你已弃牌':'You folded','AI 正在完成本局':'AI players are finishing the hand.','弃牌':'Fold','跟注':'Call','过牌':'Check','加注筹码':'Raise amount','加注减少十':'Decrease raise by ten','加注增加十':'Increase raise by ten','半池':'Half pot','一池':'Pot','全下':'All-in','加注':'Raise','正在布置牌桌':'Setting up the table','入座已备，请开始第一局':'Your seat is ready. Start the first hand.','等待':'Waiting','签到 +1,000':'Bonus +1,000','每日签到成功 · 获得 1,000 筹码':'Daily bonus claimed · 1,000 chips added','赢得底池':'Wins pot','其余玩家均已弃牌':'All other players folded','已弃牌':'Folded','轮到你行动':'Your turn','AI 继续对局':'AI players continue','正在研判牌局…':' is thinking…','加注至':'Raises to','有人加注至':'Raise to','请跟注、再加注或弃牌':'call, re-raise, or fold','筹码已经输光，请先领取每日签到':'Out of chips. Claim the daily bonus first.','筹码已经输光，下一次美东时间 00:00 可签到':'Out of chips. Next bonus at 00:00 ET.','已入局':'In hand','大盲':'Big blind','小盲':'Small blind','洗牌并发牌':'Shuffle and deal','准备':'Ready','牌桌':'Table','结算':'Result'
  };

  const common={
    ja:{'Game lobby':'ゲームロビー','Easy':'かんたん','Medium':'ふつう','Hard':'むずかしい','New game':'新しいゲーム','Hint':'ヒント','Daily challenge':'デイリーチャレンジ','Difficulty':'難易度','Moves':'手数','Completed':'完成','Time':'タイム','Play again':'もう一度','Start a match':'対局開始','Players':'人数','AI coach':'AIコーチ','Enter table':'卓に入る','Opponent is thinking…':'相手が考えています…','Pass':'パス','Points':'点','Racing':'レーシング','Track':'コース','Time trial':'タイムアタック','Start driving':'走行開始','Session paused':'一時停止','Resume':'再開','Restart':'やり直す','Return to menu':'メニューに戻る','Pot':'ポット','Pre-flop':'プリフロップ','Flop':'フロップ','Turn':'ターン','River':'リバー','Thinking':'考え中','Fold':'フォールド','Call':'コール','Check':'チェック','Raise':'レイズ','Start next hand':'次のハンド'},
    fr:{'Game lobby':'Salon de jeux','Easy':'Facile','Medium':'Moyen','Hard':'Difficile','New game':'Nouvelle partie','Hint':'Indice','Daily challenge':'Défi quotidien','Difficulty':'Difficulté','Moves':'Coups','Completed':'Terminé','Time':'Temps','Play again':'Rejouer','Start a match':'Commencer','Players':'Joueurs','AI coach':'Coach IA','Enter table':'Entrer à la table','Opponent is thinking…':"L’adversaire réfléchit…",'Pass':'Passer','Points':'Points','Racing':'Course','Track':'Circuit','Time trial':'Contre-la-montre','Start driving':'Piloter','Session paused':'Course en pause','Resume':'Reprendre','Restart':'Recommencer','Return to menu':'Retour au menu','Pot':'Pot','Pre-flop':'Pré-flop','Thinking':'Réflexion','Fold':'Se coucher','Call':'Suivre','Check':'Parole','Raise':'Relancer','Start next hand':'Nouvelle main'},
    es:{'Game lobby':'Sala de juegos','Easy':'Fácil','Medium':'Medio','Hard':'Difícil','New game':'Nueva partida','Hint':'Pista','Daily challenge':'Reto diario','Difficulty':'Dificultad','Moves':'Movimientos','Completed':'Completado','Time':'Tiempo','Play again':'Jugar de nuevo','Start a match':'Empezar partida','Players':'Jugadores','AI coach':'Entrenador IA','Enter table':'Entrar a la mesa','Opponent is thinking…':'El rival está pensando…','Pass':'Pasar','Points':'Puntos','Racing':'Carreras','Track':'Circuito','Time trial':'Contrarreloj','Start driving':'Conducir','Session paused':'Carrera en pausa','Resume':'Continuar','Restart':'Reiniciar','Return to menu':'Volver al menú','Pot':'Bote','Pre-flop':'Preflop','Thinking':'Pensando','Fold':'Retirarse','Call':'Igualar','Check':'Pasar','Raise':'Subir','Start next hand':'Nueva mano'},
    ru:{'Game lobby':'Игровой зал','Easy':'Легко','Medium':'Средне','Hard':'Сложно','New game':'Новая игра','Hint':'Подсказка','Daily challenge':'Ежедневное испытание','Difficulty':'Сложность','Moves':'Ходы','Completed':'Готово','Time':'Время','Play again':'Ещё раз','Start a match':'Начать матч','Players':'Игроки','AI coach':'ИИ-тренер','Enter table':'Сесть за стол','Opponent is thinking…':'Соперник думает…','Pass':'Пропустить','Points':'Очки','Racing':'Гонки','Track':'Трасса','Time trial':'Заезд на время','Start driving':'Старт','Session paused':'Заезд приостановлен','Resume':'Продолжить','Restart':'Заново','Return to menu':'В меню','Pot':'Банк','Pre-flop':'Префлоп','Thinking':'Думает','Fold':'Фолд','Call':'Колл','Check':'Чек','Raise':'Рейз','Start next hand':'Новая раздача'},
    it:{'Game lobby':'Sala giochi','Easy':'Facile','Medium':'Medio','Hard':'Difficile','New game':'Nuova partita','Hint':'Suggerimento','Daily challenge':'Sfida giornaliera','Difficulty':'Difficoltà','Moves':'Mosse','Completed':'Completato','Time':'Tempo','Play again':'Gioca ancora','Start a match':'Inizia partita','Players':'Giocatori','AI coach':'Coach IA','Enter table':'Entra al tavolo','Opponent is thinking…':"L’avversario pensa…",'Pass':'Passa','Points':'Punti','Racing':'Corse','Track':'Pista','Time trial':'Prova a tempo','Start driving':'Guida','Session paused':'Gara in pausa','Resume':'Continua','Restart':'Ricomincia','Return to menu':'Torna al menu','Pot':'Piatto','Pre-flop':'Pre-flop','Thinking':'Pensa','Fold':'Fold','Call':'Call','Check':'Check','Raise':'Raise','Start next hand':'Nuova mano'},
    ar:{'Game lobby':'صالة الألعاب','Easy':'سهل','Medium':'متوسط','Hard':'صعب','New game':'لعبة جديدة','Hint':'تلميح','Daily challenge':'التحدي اليومي','Difficulty':'الصعوبة','Moves':'الحركات','Completed':'مكتمل','Time':'الوقت','Play again':'العب مجددا','Start a match':'ابدأ مباراة','Players':'اللاعبون','AI coach':'مدرب ذكي','Enter table':'ادخل الطاولة','Opponent is thinking…':'الخصم يفكر…','Pass':'تجاوز','Points':'النقاط','Racing':'سباق','Track':'الحلبة','Time trial':'ضد الساعة','Start driving':'ابدأ القيادة','Session paused':'السباق متوقف','Resume':'متابعة','Restart':'إعادة','Return to menu':'القائمة','Pot':'مجموع الرهان','Pre-flop':'قبل الفلوب','Thinking':'يفكر','Fold':'انسحاب','Call':'مجاراة','Check':'تمرير','Raise':'زيادة','Start next hand':'يد جديدة'},
    ko:{'Game lobby':'게임 로비','Easy':'쉬움','Medium':'보통','Hard':'어려움','New game':'새 게임','Hint':'힌트','Daily challenge':'일일 도전','Difficulty':'난이도','Moves':'이동','Completed':'완료','Time':'시간','Play again':'다시 하기','Start a match':'대국 시작','Players':'인원','AI coach':'AI 코치','Enter table':'테이블 입장','Opponent is thinking…':'상대가 생각 중…','Pass':'패스','Points':'점수','Racing':'레이싱','Track':'트랙','Time trial':'타임 트라이얼','Start driving':'주행 시작','Session paused':'일시 정지','Resume':'계속','Restart':'다시 시작','Return to menu':'메뉴로','Pot':'팟','Pre-flop':'프리플롭','Thinking':'생각 중','Fold':'폴드','Call':'콜','Check':'체크','Raise':'레이즈','Start next hand':'다음 핸드'},
    'zh-TW':{'Game lobby':'遊戲大廳','Return to game lobby':'返回遊戲大廳','Spider Solitaire':'蜘蛛紙牌','Easy':'簡單','Medium':'中等','Hard':'困難','One suit':'單花色','Two suits':'雙花色','Four suits':'四花色','New game':'新遊戲','Hint':'提示','Daily challenge':'每日挑戰','Difficulty':'難度','Moves':'步數','Completed':'已完成','Time':'本局用時','Play again':'再來一局','Mahjong':'麻雀','Start a match':'開始一局','Players':'人數','Four-player':'四人麻將','Three-player':'三人麻將','AI coach':'AI 教練','Enter table':'進入牌桌','Opponent is thinking…':'對手思考中…','Tsumo':'自摸','Ron':'榮和','Kan':'槓','Pass':'跳過','Draw':'流局','Yaku':'役種','Points':'點數','Racing':'賽車','Track':'賽道','Time trial':'計時賽','Start driving':'開始駕駛','Session paused':'比賽暫停','Resume':'繼續','Restart':'重新開始','Return to menu':'返回選單','Pot':'底池','Pre-flop':'翻牌前','Flop':'翻牌','Turn':'轉牌','River':'河牌','Thinking':'思考中','Fold':'棄牌','Call':'跟注','Check':'過牌','Raise':'加注','Start next hand':'開始新一局'},
    pt:{'Game lobby':'Salão de jogos','Easy':'Fácil','Medium':'Médio','Hard':'Difícil','New game':'Novo jogo','Hint':'Dica','Daily challenge':'Desafio diário','Difficulty':'Dificuldade','Moves':'Jogadas','Completed':'Concluído','Time':'Tempo','Play again':'Jogar de novo','Start a match':'Iniciar partida','Players':'Jogadores','AI coach':'Treinador IA','Enter table':'Entrar na mesa','Opponent is thinking…':'O adversário está pensando…','Pass':'Passar','Points':'Pontos','Racing':'Corrida','Track':'Pista','Time trial':'Contrarrelógio','Start driving':'Dirigir','Session paused':'Corrida pausada','Resume':'Continuar','Restart':'Reiniciar','Return to menu':'Voltar ao menu','Pot':'Pote','Pre-flop':'Pré-flop','Thinking':'Pensando','Fold':'Desistir','Call':'Pagar','Check':'Mesa','Raise':'Aumentar','Start next hand':'Nova mão'}
  };
  const localize=value=>common[locale]?.[value]||value;
  const entries=Object.entries(en).sort((a,b)=>b[0].length-a[0].length);
  const han=/[\u3400-\u9fff]/g;
  function translate(value){if(!value||locale==='zh-CN')return value;let result=String(value);for(const[source,english]of entries)if(result.includes(source))result=result.split(source).join(localize(english));han.lastIndex=0;if(!han.test(result))return result;han.lastIndex=0;if(locale==='zh-TW')return result.replaceAll('车','車').replaceAll('赛','賽').replaceAll('游','遊').replaceAll('戏','戲').replaceAll('对','對').replaceAll('开','開').replaceAll('发','發').replaceAll('张','張').replaceAll('这','這').replaceAll('里','裡').replaceAll('后','後').replaceAll('进','進').replaceAll('录','錄').replaceAll('当','當').replaceAll('与','與').replaceAll('为','為').replaceAll('时','時').replaceAll('点','點').replaceAll('场','場').replaceAll('来','來').replaceAll('个','個').replaceAll('号','號').replaceAll('动','動').replaceAll('国','國').replaceAll('际','際').replaceAll('还','還').replaceAll('显','顯').replaceAll('将','將').replaceAll('听','聽').replaceAll('杠','槓');return result.replace(han,'')}
  function translateElement(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(node=>{if(node.parentElement?.closest('script,style'))return;const next=translate(node.nodeValue);if(next!==node.nodeValue)node.nodeValue=next});const attrNodes=[];if(root.matches?.('[title],[aria-label],[placeholder]'))attrNodes.push(root);root.querySelectorAll?.('[title],[aria-label],[placeholder]').forEach(el=>attrNodes.push(el));attrNodes.forEach(el=>['title','aria-label','placeholder'].forEach(attr=>{if(el.hasAttribute(attr))el.setAttribute(attr,translate(el.getAttribute(attr)))}))}
  function installPicker(){if(document.querySelector('.game-language-picker'))return;const label=document.createElement('label');label.className='game-language-picker';label.setAttribute('aria-label','Language');const icon=document.createElement('span');icon.textContent='🌐';const select=document.createElement('select');supported.forEach(code=>{const option=document.createElement('option');option.value=code;option.textContent=labels[code];option.selected=code===locale;select.append(option)});select.addEventListener('change',()=>{localStorage.setItem('tzt-game-language',select.value);const next=new URL(location.href);next.searchParams.set('lang',select.value);location.href=next.href});label.append(icon,select);document.body.append(label)}
  const style=document.createElement('style');style.textContent='.game-language-picker{position:fixed;right:max(10px,env(safe-area-inset-right));bottom:max(10px,env(safe-area-inset-bottom));z-index:99999;display:flex;align-items:center;gap:6px;padding:6px 9px;border:2px solid rgba(255,255,255,.9);border-radius:999px;background:rgba(18,61,82,.9);box-shadow:0 5px 0 rgba(8,58,70,.22);color:#fff;font:700 12px/1 system-ui,sans-serif;backdrop-filter:blur(10px)}.game-language-picker select{max-width:112px;border:0;outline:0;background:transparent;color:#fff;font:inherit}.game-language-picker option{color:#142f3b;background:#fff}body:has(.poker-table) .game-language-picker{bottom:auto;top:max(88px,calc(env(safe-area-inset-top) + 76px))}[dir=rtl] .game-language-picker{right:auto;left:max(10px,env(safe-area-inset-left))}@media(max-width:620px){.game-language-picker{padding:5px 7px}.game-language-picker select{max-width:86px;font-size:11px}body:has(.poker-table) .game-language-picker{top:max(76px,calc(env(safe-area-inset-top) + 70px))}}';document.head.append(style);
  const confirmOriginal=window.confirm.bind(window);window.confirm=message=>confirmOriginal(translate(message));
  if(window.CanvasRenderingContext2D){const fill=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...rest){return fill.call(this,translate(text),...rest)};const stroke=CanvasRenderingContext2D.prototype.strokeText;CanvasRenderingContext2D.prototype.strokeText=function(text,...rest){return stroke.call(this,translate(text),...rest)}}
  function boot(){document.documentElement.lang=window.__TZT_GAME_LOCALE;document.documentElement.dir=locale==='ar'?'rtl':'ltr';translateElement(document.body);installPicker();new MutationObserver(records=>{records.forEach(record=>{if(record.type==='characterData'){const next=translate(record.target.nodeValue);if(next!==record.target.nodeValue)record.target.nodeValue=next}else record.addedNodes.forEach(node=>{if(node.nodeType===1)translateElement(node);else if(node.nodeType===3)node.nodeValue=translate(node.nodeValue)})});if(document.documentElement.lang!==window.__TZT_GAME_LOCALE)document.documentElement.lang=window.__TZT_GAME_LOCALE;if(!document.querySelector('.game-language-picker'))installPicker()}).observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['lang']});setTimeout(installPicker,600)}
  window.GAME_I18N={getLocale:()=>locale,translate,supported};if(document.readyState==='complete')setTimeout(boot,900);else window.addEventListener('load',()=>setTimeout(boot,900),{once:true});
})();
