import{createBoard,isWon,placeMines,reveal,toggleFlag}from"./engine.js";import{dateKey,hashSeed,loadRecords,recordCompletion,saveRecords,seededRandom}from"./daily.js";
const levels={easy:{rows:9,cols:9,mines:10},medium:{rows:16,cols:16,mines:40},hard:{rows:16,cols:30,mines:99}};const host=document.querySelector("#board"),remaining=document.querySelector("#remaining"),time=document.querySelector("#time"),message=document.querySelector("#message"),dailyButton=document.querySelector("#dailyButton"),dailyStatus=document.querySelector("#dailyStatus"),dailyList=document.querySelector("#dailyRecords");let level="easy",board,started=false,ended=false,mode="reveal",seconds=0,timer=null,pressTimer=null,longPressed=false,pressPoint=null,dailyMode=false,records=loadRecords();
function flags(){return board.flat().filter(c=>c.flagged).length}function formatTime(value){return`${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`}function renderRecords(){const today=records.find(item=>item.date===dateKey());dailyStatus.textContent=today?`今日最佳 ${formatTime(today.seconds)}`:"今日尚未完成";dailyList.innerHTML=records.length?records.map((item,index)=>`<li><i>${index+1}</i><strong>${item.date}</strong><time>${formatTime(item.seconds)}</time></li>`).join(""):'<li class="empty">完成每日挑战后，这里会记录你的完成速度</li>'}
function render(){host.style.setProperty("--cols",levels[level].cols);host.replaceChildren(...board.flat().map(cell=>{const button=document.createElement("button");button.className=`cell${cell.revealed?" revealed":""}${cell.flagged?" flagged":""}${cell.revealed&&cell.mine?" mine":""}`;button.dataset.row=cell.row;button.dataset.col=cell.col;if(cell.revealed){button.textContent=cell.mine?"✹":cell.adjacent||"";button.dataset.n=cell.adjacent}else if(cell.flagged)button.textContent="🚩";button.setAttribute("aria-label",`第 ${cell.row+1} 行第 ${cell.col+1} 列${cell.flagged?"，已插旗":""}`);return button;}));remaining.textContent=levels[level].mines-flags()}
function begin(row,col){if(started)return;started=true;if(!dailyMode)placeMines(board,levels[level].mines,row,col);timer=setInterval(()=>{seconds=Math.min(999,seconds+1);time.textContent=String(seconds).padStart(3,"0")},1000)}
function finish(win){ended=true;clearInterval(timer);if(win){seconds=Math.max(1,seconds);message.textContent=`排雷成功！用时 ${seconds} 秒`;board.flat().filter(c=>c.mine).forEach(c=>c.flagged=true);if(dailyMode){records=saveRecords(recordCompletion(records,{date:dateKey(),seconds}));renderRecords()}}else{message.textContent="踩到地雷了，再试一次";board.flat().filter(c=>c.mine).forEach(c=>c.revealed=true)}render()}
function revealAt(row,col){if(ended)return;begin(row,col);const result=reveal(board,row,col);if(result.hitMine)return finish(false);if(result.changed&&isWon(board))return finish(true);render()}function flagAt(row,col){if(ended)return;begin(row,col);toggleFlag(board,row,col);message.textContent="旗帜用来标记你认为有雷的位置";render()}
function start(options={}){clearInterval(timer);dailyMode=Boolean(options.daily);level=dailyMode?"medium":level;const config=levels[level];board=createBoard(config.rows,config.cols);if(dailyMode){placeMines(board,config.mines,Math.floor(config.rows/2),Math.floor(config.cols/2),seededRandom(hashSeed(`minesweeper-${dateKey()}`)));reveal(board,Math.floor(config.rows/2),Math.floor(config.cols/2))}started=false;ended=false;seconds=0;time.textContent="000";message.textContent=dailyMode?"今日固定雷区 · 按完成速度进入排行榜":"首格一定安全，放心开始";dailyButton.classList.toggle("active",dailyMode);document.querySelectorAll("[data-level]").forEach(button=>{button.disabled=dailyMode;button.classList.toggle("active",button.dataset.level===level)});render()}
host.addEventListener("click",e=>{if(longPressed){longPressed=false;return}const cell=e.target.closest(".cell");if(!cell)return;const row=Number(cell.dataset.row),col=Number(cell.dataset.col);mode==="flag"?flagAt(row,col):revealAt(row,col)});host.addEventListener("contextmenu",e=>{const cell=e.target.closest(".cell");if(!cell)return;e.preventDefault();flagAt(Number(cell.dataset.row),Number(cell.dataset.col))});host.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse")return;const cell=e.target.closest(".cell");if(!cell)return;longPressed=false;pressPoint={x:e.clientX,y:e.clientY};pressTimer=setTimeout(()=>{longPressed=true;navigator.vibrate?.(35);flagAt(Number(cell.dataset.row),Number(cell.dataset.col))},430)});host.addEventListener("pointermove",e=>{if(pressPoint&&Math.hypot(e.clientX-pressPoint.x,e.clientY-pressPoint.y)>10)clearTimeout(pressTimer)});["pointerup","pointercancel"].forEach(type=>host.addEventListener(type,()=>{clearTimeout(pressTimer);pressPoint=null}));
document.querySelectorAll("[data-level]").forEach(button=>button.addEventListener("click",()=>{level=button.dataset.level;start()}));document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>{mode=button.dataset.mode;document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b===button));message.textContent=mode==="flag"?"插旗模式：点击格子标记地雷":"翻开模式：点击格子进行排雷"}));dailyButton.addEventListener("click",()=>start({daily:true}));document.querySelector("#newGame").addEventListener("click",()=>start());renderRecords();start();
