import{createBoard,isWon,placeMines,reveal,toggleFlag}from"./engine.js";
const levels={easy:{rows:9,cols:9,mines:10},medium:{rows:16,cols:16,mines:40},hard:{rows:16,cols:30,mines:99}};const host=document.querySelector("#board"),remaining=document.querySelector("#remaining"),time=document.querySelector("#time"),message=document.querySelector("#message");let level="easy",board,started=false,ended=false,mode="reveal",seconds=0,timer=null,pressTimer=null,longPressed=false,pressPoint=null;
function flags(){return board.flat().filter(c=>c.flagged).length}function render(){host.style.setProperty("--cols",levels[level].cols);host.replaceChildren(...board.flat().map(cell=>{const button=document.createElement("button");button.className=`cell${cell.revealed?" revealed":""}${cell.flagged?" flagged":""}${cell.revealed&&cell.mine?" mine":""}`;button.dataset.row=cell.row;button.dataset.col=cell.col;if(cell.revealed){button.textContent=cell.mine?"✹":cell.adjacent||"";button.dataset.n=cell.adjacent}else if(cell.flagged)button.textContent="🚩";button.setAttribute("aria-label",`第 ${cell.row+1} 行第 ${cell.col+1} 列${cell.flagged?"，已插旗":""}`);return button;}));remaining.textContent=levels[level].mines-flags()}
function begin(row,col){if(started)return;started=true;placeMines(board,levels[level].mines,row,col);timer=setInterval(()=>{seconds=Math.min(999,seconds+1);time.textContent=String(seconds).padStart(3,"0")},1000)}
function finish(win){ended=true;clearInterval(timer);if(win){message.textContent=`排雷成功！用时 ${seconds} 秒`;board.flat().filter(c=>c.mine).forEach(c=>c.flagged=true)}else{message.textContent="踩到地雷了，再试一次";board.flat().filter(c=>c.mine).forEach(c=>c.revealed=true)}render()}
function revealAt(row,col){if(ended)return;begin(row,col);const result=reveal(board,row,col);if(result.hitMine)return finish(false);if(result.changed&&isWon(board))return finish(true);render()}
function flagAt(row,col){if(ended)return;toggleFlag(board,row,col);message.textContent="旗帜用来标记你认为有雷的位置";render()}
function start(){clearInterval(timer);const config=levels[level];board=createBoard(config.rows,config.cols);started=false;ended=false;seconds=0;time.textContent="000";message.textContent="首格一定安全，放心开始";render()}
host.addEventListener("click",e=>{if(longPressed){longPressed=false;return}const cell=e.target.closest(".cell");if(!cell)return;const row=Number(cell.dataset.row),col=Number(cell.dataset.col);mode==="flag"?flagAt(row,col):revealAt(row,col)});host.addEventListener("contextmenu",e=>{const cell=e.target.closest(".cell");if(!cell)return;e.preventDefault();flagAt(Number(cell.dataset.row),Number(cell.dataset.col))});host.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse")return;const cell=e.target.closest(".cell");if(!cell)return;longPressed=false;pressPoint={x:e.clientX,y:e.clientY};pressTimer=setTimeout(()=>{longPressed=true;navigator.vibrate?.(35);flagAt(Number(cell.dataset.row),Number(cell.dataset.col))},430)});host.addEventListener("pointermove",e=>{if(pressPoint&&Math.hypot(e.clientX-pressPoint.x,e.clientY-pressPoint.y)>10)clearTimeout(pressTimer)});["pointerup","pointercancel"].forEach(type=>host.addEventListener(type,()=>{clearTimeout(pressTimer);pressPoint=null}));
document.querySelectorAll("[data-level]").forEach(button=>button.addEventListener("click",()=>{level=button.dataset.level;document.querySelectorAll("[data-level]").forEach(b=>b.classList.toggle("active",b===button));start()}));document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>{mode=button.dataset.mode;document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b===button));message.textContent=mode==="flag"?"插旗模式：点击格子标记地雷":"翻开模式：点击格子进行排雷"}));document.querySelector("#newGame").addEventListener("click",start);start();
